const constants = {
    SET_SONG_DATA: "SET_SONG_DATA",
    SET_SONG_DURATION: "SET_SONG_DURATION",
    SET_LYRICS_DATA: "SET_LYRICS_DATA",
    SET_PLAYLIST_DATA: "SET_PLAYLIST_DATA",
    FETCH_PLAYLIST_BEGIN: "FETCH_PLAYLIST_BEGIN",
    FETCH_PLAYLIST_FAILURE: "FETCH_PLAYLIST_FAILURE",
    SET_CURRENT_SONG_INDEX: "SET_CURRENT_SONG_INDEX",
    SET_AUDIO_DATA: "SET_AUDIO_DATA",
    SET_PLAY_STATE: "SET_PLAY_STATE",
    SHOW_PLAYLIST: "SHOW_PLAYLIST"
}
export default constants;